/**
 * @File Name          : IETRS_InspScheConfigDuplicateCheck.cls
 * @Description        : Check Inspection Config duplicates upon creating new record
 * @Author             : Ariel Zhang
 * @Group              :
 * @Last Modified By   : Ariel Zhang
 * @Last Modified On   : 07/19/2023
 * @Modification Log   :
 * Ver      Date            Author          	Modification
 * 1.0      07/19/2023      Ariel Zhang       Initial Version
 **/

 public class IETRS_InspScheConfigDuplicateCheck{

  @InvocableMethod(label= 'Check InspectionScheduleConfig duplicate')
  public static void testPlaceHolder() {

  }
 }